pip install ./aws_dwconnector --upgrade
pip install ./aws_s3connector --upgrade
pip install ./aws_dynamodbconnector --upgrade
pip install ./aws_sqsconnector --upgrade
pip install ./aws_nsconnector --upgrade
pip install ./aws_b2bsoftconnector --upgrade
pip install ./aws_iqmetrixconnector --upgrade
pip install ./aws_repairdeskconnector --upgrade
pip install ./aws_mage2connector --upgrade
pip install ./datawald_abstract --upgrade
pip install ./datawald_backoffice --upgrade
pip install ./datawald_frontend --upgrade
pip install ./datawald_s3agency --upgrade
pip install ./datawald_dynamodbagency --upgrade
pip install ./datawald_sqsagency --upgrade
pip install ./datawald_nsagency --upgrade
pip install ./datawald_b2bsoftagency --upgrade
pip install ./datawald_iqmetrixagency --upgrade
pip install ./datawald_repairdeskagency --upgrade
pip install ./datawald_mage2agency --upgrade
