pip uninstall AWS-DWConnector
pip uninstall AWS-S3Connector
pip uninstall AWS-DynamoDBConnector
pip uninstall AWS-SQSConnector
pip uninstall AWS-NSConnector
pip uninstall AWS-B2BSoftConnector
pip uninstall AWS-IQMetrixConnector
pip uninstall AWS-RepairDeskConnector
pip uninstall AWS-Mage2Connector
pip uninstall DataWald-Abstract
pip uninstall DataWald-BackOffice
pip uninstall DataWald-Frontend
pip uninstall DataWald-S3Agency
pip uninstall DataWald-DynamoDBAgency
pip uninstall DataWald-SQSAgency
pip uninstall DataWald-NSAgency
pip uninstall DataWald-B2BSoftAgency
pip uninstall DataWald-IQMetrixAgency
pip uninstall DataWald-RepairDeskAgency
pip uninstall DataWald-Mage2Agency
